import { NextResponse } from "next/server";
import { db } from "@/db";
import { invoices, contacts, customers, projects, qboTokens } from "@/db/schema";
import { eq, and } from "drizzle-orm";
import { getValidGmailToken, createGmailDraft } from "@/lib/gmail";

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function daysFromDate(dateStr: string): number {
  // Positive = overdue, negative = not yet due
  const due = new Date(dateStr + "T12:00:00Z").getTime();
  return Math.floor((Date.now() - due) / 86400000);
}

const PROTECTED_STAGES = ["Disputed", "On Hold", "Escalated"];
const PAUSE_STAGES     = ["Disputed", "On Hold", "Promised", "Promise to Pay"];

/** Returns the reminder type for today, or null if no reminder should fire */
function getReminderType(daysOverdue: number): string | null {
  if (daysOverdue === -3) return "pre-due";       // 3 days before due
  if (daysOverdue === 1)  return "first-notice";  // 1 day overdue
  if (daysOverdue === 8)  return "second-notice"; // 8 days overdue
  if (daysOverdue === 21) return "final-notice";  // 21 days overdue
  return null;
}

const REMINDER_SUBJECTS: Record<string, string> = {
  "pre-due":      "Upcoming Payment Reminder",
  "first-notice": "Payment Reminder — Invoice Overdue",
  "second-notice":"Second Reminder — Outstanding Invoice",
  "final-notice": "Urgent Reminder — Outstanding Invoice",
};

const REMINDER_BODY = (name: string, lines: string[]) =>
  `Hi ${name},\n\nI hope you are well. Please accept our apologies if you have already taken care of this — this is an automated email generated by our system based on the age of the invoice${lines.length > 1 ? "s" : ""} below, and we appreciate it may cross with a payment already in progress.\n\nOur records show the following invoice${lines.length > 1 ? "s" : ""} currently outstanding on your account:\n\n${lines.join("\n")}\n\nIf payment has already been arranged, please disregard this message entirely — we truly value your continued partnership and apologise for any inconvenience.\n\nIf you have any queries or would like to discuss payment arrangements, please don't hesitate to get in touch and we will be happy to help.\n\nMany thanks`;

// All reminder types share the same friendly body — only the subject line varies.
const REMINDER_BODIES: Record<string, (name: string, lines: string[]) => string> = {
  "pre-due":      REMINDER_BODY,
  "first-notice": REMINDER_BODY,
  "second-notice":REMINDER_BODY,
  "final-notice": REMINDER_BODY,
};

async function getRefreshedQboToken(orgId: string) {
  const [token] = await db.select().from(qboTokens).where(eq(qboTokens.orgId, orgId)).limit(1);
  if (!token) return null;
  const now = Date.now();
  if (new Date(token.accessTokenExpiresAt).getTime() - now < 5 * 60 * 1000) {
    const res = await fetch("https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer", {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        Authorization: `Basic ${Buffer.from(`${process.env.QBO_CLIENT_ID}:${process.env.QBO_CLIENT_SECRET}`).toString("base64")}`,
      },
      body: new URLSearchParams({ grant_type: "refresh_token", refresh_token: token.refreshToken }),
    });
    if (!res.ok) return token;
    const d = await res.json();
    await db.update(qboTokens).set({
      accessToken: d.access_token,
      refreshToken: d.refresh_token || token.refreshToken,
      accessTokenExpiresAt: new Date(now + (d.expires_in || 3600) * 1000),
      updatedAt: new Date(),
    }).where(eq(qboTokens.orgId, orgId));
    return { ...token, accessToken: d.access_token };
  }
  return token;
}

// ─────────────────────────────────────────────────────────────────────────────
// CRON HANDLER
// ─────────────────────────────────────────────────────────────────────────────
export async function GET(req: Request) {
  const authHeader = req.headers.get("authorization");
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const today = new Date().toISOString().slice(0, 10);
  let escalated = 0;
  let remindersSent = 0;
  let reminderErrors: string[] = [];

  // ── 1. Stage escalation (existing logic) ──────────────────────────────────
  const allInvoices = await db.select().from(invoices);

  for (const inv of allInvoices) {
    if (inv.paymentStatus === "Paid" || inv.paymentStatus === "Written Off") continue;
    const daysOverdue = daysFromDate(inv.dueDate);
    if (daysOverdue > 30 && !PROTECTED_STAGES.includes(inv.collectionStage)) {
      await db.update(invoices)
        .set({ collectionStage: "Escalated", updatedAt: new Date() })
        .where(eq(invoices.id, inv.id));
      escalated++;
    }
  }

  // ── 2. Create Gmail drafts (one per triggered contact, per org) ──────────
  // Drafts land in the connected Gmail account — user reviews and sends manually.
  const allOrgs = [...new Set(allInvoices.map((inv) => inv.orgId))];

  for (const orgId of allOrgs) {
    try {
      const gmailToken = await getValidGmailToken(orgId).catch(() => null);
      if (!gmailToken) continue; // Gmail not connected for this org — skip

      const autoContacts = await db.select().from(contacts)
        .where(and(eq(contacts.orgId, orgId), eq(contacts.receivesAuto, true)));
      const enabledContacts = autoContacts.filter((c) => c.email);
      if (enabledContacts.length === 0) continue;

      for (const contact of enabledContacts) {
        try {
          const relatedInvoices = allInvoices.filter((inv) => {
            if (inv.orgId !== orgId) return false;
            if (inv.paymentStatus === "Paid" || inv.paymentStatus === "Written Off") return false;
            if ((inv.total - (inv.paid || 0)) <= 0) return false;
            if (PAUSE_STAGES.includes(inv.collectionStage)) return false;
            if (contact.projectId) return inv.projectId === contact.projectId;
            return inv.customerId === contact.customerId;
          });

          if (relatedInvoices.length === 0) continue;

          const triggeredInvoices = relatedInvoices.filter((inv) => getReminderType(daysFromDate(inv.dueDate)) !== null);
          if (triggeredInvoices.length === 0) continue;

          const typePriority = ["final-notice", "second-notice", "first-notice", "pre-due"];
          const types = triggeredInvoices.map((inv) => getReminderType(daysFromDate(inv.dueDate))!);
          const reminderType = typePriority.find((t) => types.includes(t)) ?? types[0];

          let entityRef = "";
          if (contact.projectId) {
            const [proj] = await db.select().from(projects).where(eq(projects.id, contact.projectId)).limit(1);
            entityRef = proj?.code ?? "";
          } else {
            const [cust] = await db.select().from(customers).where(eq(customers.id, contact.customerId)).limit(1);
            entityRef = cust?.code ?? "";
          }

          const invRefs = triggeredInvoices.map((inv) => inv.invoiceNumber).join(", ");
          const subjectParts = [REMINDER_SUBJECTS[reminderType]];
          if (entityRef) subjectParts.push(entityRef);
          subjectParts.push(`Ref: ${invRefs}`);
          const subject = subjectParts.join(" | ");

          const invoiceLines = triggeredInvoices.map((inv) => {
            const balance = inv.total - (inv.paid || 0);
            const d = daysFromDate(inv.dueDate);
            const overdueStr = d > 0 ? `${d} days overdue` : d === 0 ? "due today" : `due in ${Math.abs(d)} days`;
            return `  • ${inv.invoiceNumber} — Balance: ${balance.toLocaleString("en-IE", { style: "currency", currency: inv.currency || "EUR" })} (${overdueStr})`;
          });

          const greeting = contact.name?.split(" ")[0] || "Sir/Madam";
          const body = REMINDER_BODIES[reminderType](greeting, invoiceLines);

          await createGmailDraft(gmailToken.accessToken, gmailToken.email, contact.email!, subject, body);
          remindersSent++;
        } catch (contactErr: any) {
          reminderErrors.push(`Contact ${contact.email}: ${contactErr.message}`);
        }
      }
    } catch (orgErr: any) {
      reminderErrors.push(`Org ${orgId}: ${orgErr.message}`);
    }
  }

  return NextResponse.json({
    ran: today,
    escalated,
    draftsCreated: remindersSent,
    errors: reminderErrors.length > 0 ? reminderErrors : undefined,
  });
}
