/**
 * POST /api/cron/trigger
 *
 * Manually create Gmail drafts for the requesting org.
 * Protected by normal session auth — no CRON_SECRET needed.
 *
 * Unlike the scheduled cron, fires for every open invoice that meets ANY
 * reminder threshold (pre-due ≤ 3 days, or overdue ≥ 1 day).
 * Drafts land in the connected Gmail account — the user reviews and sends
 * each one manually.
 *
 * Body: { dryRun?: boolean }
 *   dryRun = true  → preview what drafts would be created, create nothing
 *   dryRun = false → create Gmail drafts and return the list
 *
 * Response:
 *   { drafted: number, skipped: number, dryRun: boolean,
 *     details: { contact, entity, invoices, reminderType, drafted, error? }[] }
 */

import { NextResponse } from "next/server";
import { db } from "@/db";
import { invoices, contacts, customers, projects } from "@/db/schema";
import { eq, and } from "drizzle-orm";
import { requireOrg } from "@/lib/api";
import { getValidGmailToken, createGmailDraft } from "@/lib/gmail";

// ─── shared helpers (mirrors cron/route.ts) ───────────────────────────────────

function daysFromDate(dateStr: string): number {
  const due = new Date(dateStr + "T12:00:00Z").getTime();
  return Math.floor((Date.now() - due) / 86400000);
}

const PAUSE_STAGES = ["Disputed", "On Hold", "Promised", "Promise to Pay"];

/** For manual trigger: fire for any invoice that is pre-due (≤3 days) or overdue */
function getReminderType(daysOverdue: number): string | null {
  if (daysOverdue <= -1 && daysOverdue >= -3) return "pre-due";
  if (daysOverdue >= 1 && daysOverdue < 8)   return "first-notice";
  if (daysOverdue >= 8 && daysOverdue < 21)  return "second-notice";
  if (daysOverdue >= 21)                     return "final-notice";
  return null;
}

const REMINDER_SUBJECTS: Record<string, string> = {
  "pre-due":      "Upcoming Payment Reminder",
  "first-notice": "Payment Reminder — Invoice Overdue",
  "second-notice":"Second Reminder — Outstanding Invoice",
  "final-notice": "Urgent Reminder — Outstanding Invoice",
};

const REMINDER_BODY = (name: string, lines: string[]) =>
  `Hi ${name},\n\nI hope you are well. Please accept our apologies if you have already taken care of this — this is an automated email generated by our system based on the age of the invoice${lines.length > 1 ? "s" : ""} below, and we appreciate it may cross with a payment already in progress.\n\nOur records show the following invoice${lines.length > 1 ? "s" : ""} currently outstanding on your account:\n\n${lines.join("\n")}\n\nIf payment has already been arranged, please disregard this message entirely — we truly value your continued partnership and apologise for any inconvenience.\n\nIf you have any queries or would like to discuss payment arrangements, please don't hesitate to get in touch and we will be happy to help.\n\nMany thanks`;

const REMINDER_BODIES: Record<string, (name: string, lines: string[]) => string> = {
  "pre-due":      REMINDER_BODY,
  "first-notice": REMINDER_BODY,
  "second-notice":REMINDER_BODY,
  "final-notice": REMINDER_BODY,
};

// ─── handler ─────────────────────────────────────────────────────────────────

export async function POST(req: Request) {
  const { error, orgId } = await requireOrg();
  if (error) return error;

  const body = await req.json().catch(() => ({}));
  const dryRun: boolean = body.dryRun === true;

  // 1. Gmail token — required for draft creation
  const gmailToken = await getValidGmailToken(orgId!).catch(() => null);
  if (!gmailToken) {
    return NextResponse.json(
      { error: "Gmail not connected. Connect Gmail in Settings → Integrations to create drafts." },
      { status: 422 },
    );
  }

  // 2. Load all auto contacts for this org
  const autoContacts = await db
    .select().from(contacts)
    .where(and(eq(contacts.orgId, orgId!), eq(contacts.receivesAuto, true)));

  const enabledContacts = autoContacts.filter((c) => c.email);
  if (enabledContacts.length === 0) {
    return NextResponse.json({ drafted: 0, skipped: 0, dryRun, details: [], message: "No contacts with automation enabled." });
  }

  // 3. Load all open invoices for this org
  const orgInvoices = await db.select().from(invoices).where(eq(invoices.orgId, orgId!));

  // 4. Process each contact
  type Detail = {
    contact: string;
    entity: string;
    reminderType: string;
    invoices: string[];
    drafted: boolean;
    error?: string;
  };
  const details: Detail[] = [];
  let drafted = 0;
  let skipped = 0;

  for (const contact of enabledContacts) {
    const relatedInvoices = orgInvoices.filter((inv) => {
      if (inv.paymentStatus === "Paid" || inv.paymentStatus === "Written Off") return false;
      if ((inv.total - (inv.paid || 0)) <= 0) return false;
      if (PAUSE_STAGES.includes(inv.collectionStage)) return false;
      if (contact.projectId) return inv.projectId === contact.projectId;
      return inv.customerId === contact.customerId;
    });

    if (relatedInvoices.length === 0) { skipped++; continue; }

    const triggeredInvoices = relatedInvoices.filter((inv) => getReminderType(daysFromDate(inv.dueDate)) !== null);
    if (triggeredInvoices.length === 0) { skipped++; continue; }

    const typePriority = ["final-notice", "second-notice", "first-notice", "pre-due"];
    const types = triggeredInvoices.map((inv) => getReminderType(daysFromDate(inv.dueDate))!);
    const reminderType = typePriority.find((t) => types.includes(t)) ?? types[0];

    let entityName = "";
    let entityRef  = "";
    if (contact.projectId) {
      const [proj] = await db.select().from(projects).where(eq(projects.id, contact.projectId)).limit(1);
      entityName = proj?.name ?? contact.projectId;
      entityRef  = proj?.code ?? "";
    } else {
      const [cust] = await db.select().from(customers).where(eq(customers.id, contact.customerId)).limit(1);
      entityName = cust?.name ?? contact.customerId;
      entityRef  = cust?.code ?? "";
    }

    const invRefs = triggeredInvoices.map((inv) => inv.invoiceNumber);
    const subjectParts = [REMINDER_SUBJECTS[reminderType]];
    if (entityRef) subjectParts.push(entityRef);
    subjectParts.push(`Ref: ${invRefs.join(", ")}`);
    const subject = subjectParts.join(" | ");

    const invoiceLines = triggeredInvoices.map((inv) => {
      const balance = inv.total - (inv.paid || 0);
      const d = daysFromDate(inv.dueDate);
      const overdueStr = d > 0 ? `${d} days overdue` : d === 0 ? "due today" : `due in ${Math.abs(d)} days`;
      return `  • ${inv.invoiceNumber} — Balance: ${balance.toLocaleString("en-IE", { style: "currency", currency: inv.currency || "EUR" })} (${overdueStr})`;
    });

    const greeting = contact.name?.split(" ")[0] || "Sir/Madam";
    const bodyText  = REMINDER_BODIES[reminderType](greeting, invoiceLines);

    const detail: Detail = { contact: contact.email!, entity: entityName, reminderType, invoices: invRefs, drafted: false };

    if (!dryRun) {
      try {
        await createGmailDraft(gmailToken.accessToken, gmailToken.email, contact.email!, subject, bodyText);
        detail.drafted = true;
        drafted++;
      } catch (e: any) {
        detail.error = e.message;
        skipped++;
      }
    } else {
      detail.drafted = true; // preview — would be drafted
      drafted++;
    }

    details.push(detail);
  }

  return NextResponse.json({ drafted, skipped, dryRun, details });
}
